### ISSUE TITLE
Make "Pause" button work

### ISSUE THREAD

**Issue by beckerdown2** [kbecker0619/cwsw_evqueue_test#7]
For the demo app (single-fixture stop light), the intended functionality for the "Pause" button is that it should hold the g-y-r-g sequence at whatever is the current lamp.

It is understood that with today's edition of the timer library, that the moment the "Pause" hold is released, the active timer will mature and the next lamp in the lighting sequence will begin.

Basic Plan:
1. Button Sensor reacts to assigned (mapped) button, emits Pause event
2. Current Stoplite State reacts to Pause

This will require updates to the Stoplite's transition table.

**Comment by beckerdown2** [comment]
Implementation of Plan Step 1: button sensor sends a `Pause` event upon receipt of a `Commit` event for the `Pause` button.

**Comment by kbecker0619** [comment]
Because of the extreme liklihood of divergence in the proto-SME instantiated in the Stoplite component, with the 2nd-edition SME instantiated in the board-level button component, I see a dependency on issue #9. Taking a quick diversion in the application of this issue while I make that problem go away.

**Comment by kbecker0619** [comment]
Upon resumption from the interruption which was #9, resumed implementation.

Chose to handle the Pause event at the SME itself, rather than in each of the states. Justified because the Pause command is meta to the states; it is supposed to pause the whole state machine at the current state.

This should be fine as long as the output device doesn't need refreshing. Even if it did, that should be handled by the Board or Arch layers, so I don't anticipate a problem.
